CC = g++		# defines a variable, called 'C'

hello: hello.cpp		#'hello' (the target) depands on 'hello.cpp'
		$(CC) -o hello hello.cpp
								# the command to build the target
clean:					#Another target
		rm -f hello *~